baseURL = 'https://blakearnold.me/'
languageCode = 'en-us'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
buildDrafts = true

[pagination]
pagerSize = 10

[languages]
[languages.en]
title = "My Corner"
weight = 1
contentDir = "content"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
