baseURL = 'https://blakearnold.me/'
languageCode = 'en-us'
title = 'Technology, Computers, Etc.'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Ananke"
weight = 1
contentDir = "content"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"